default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: appistack_development

test:
  <<: *default
  database: appistack_test

production:
  <<: *default
  database: appistack_production
  username: appistack
  password: <%= ENV['RAILS42_DATABASE_PASSWORD'] %>
