default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: voxxel_development

test:
  <<: *default
  database: voxxel_test

production:
  <<: *default
  database: voxxel_production
  username: voxxel
  password: <%= ENV['RAILS42_DATABASE_PASSWORD'] %>
