default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails42_development

test:
  <<: *default
  database: rails42_test

production:
  <<: *default
  database: rails42_production
  username: rails42
  password: <%= ENV['RAILS42_DATABASE_PASSWORD'] %>
